# Generated by Django 2.1.4 on 2018-12-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0004_auto_20181204_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='co-norm')),
            ],
        ),
        migrations.CreateModel(
            name='TNorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='t-norm')),
            ],
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='system',
            name='conorm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ide.CONorm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system',
            name='tnorm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ide.TNorm'),
            preserve_default=False,
        ),
    ]
