# Generated by Django 2.1.4 on 2018-12-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0007_auto_20181204_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=1024, verbose_name='Rule')),
            ],
        ),
        migrations.AlterModelOptions(
            name='conorm',
            options={'verbose_name': 'Co-Norm'},
        ),
        migrations.AlterModelOptions(
            name='defuzzy',
            options={'verbose_name': 'DeFuzzy'},
        ),
        migrations.AlterModelOptions(
            name='fuzzymodel',
            options={'verbose_name': 'Fuzzy Model'},
        ),
        migrations.AlterModelOptions(
            name='tnorm',
            options={'verbose_name': 'T-Norm'},
        ),
    ]
