# Generated by Django 2.1.4 on 2018-12-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0008_auto_20181204_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ide.System'),
            preserve_default=False,
        ),
    ]
